apiVersion: v1
kind: Service
metadata:
  name: api-gateway
  labels:
    app: api-gateway
spec:
  ports:
    - port: 8000
      targetPort: {{ .Values.services.apiGateway.containerPort }}
      protocol: TCP
      name: http
  selector:
    app: api-gateway
---
apiVersion: v1
kind: Service
metadata:
  name: approval-service
  labels:
    app: approval-service
spec:
  ports:
    - port: 8001
      targetPort: {{ .Values.services.approvalService.containerPort }}
      protocol: TCP
      name: http
  selector:
    app: approval-service
---
apiVersion: v1
kind: Service
metadata:
  name: notification-service
  labels:
    app: notification-service
spec:
  ports:
    - port: 8002
      targetPort: {{ .Values.services.notificationService.containerPort }}
      protocol: TCP
      name: http
  selector:
    app: notification-service
---
apiVersion: v1
kind: Service
metadata:
  name: web-frontend
  labels:
    app: web-frontend
spec:
  ports:
    - port: 3000
      targetPort: {{ .Values.services.webFrontend.containerPort }}
      protocol: TCP
      name: http
  selector:
    app: web-frontend
